/* Project file:          S01_01_APP_CRT_ADMIN_AREA_V2_LOV_dml                 */
/* Project name:          Capital Rehabilitation Tracking Reporting       */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           Database creation script                        */
/* Created on:            2021-01-14 03:03                                */
/* ---------------------------------------------------------------------- */

USE [CRT_DEV];
GO

--IDEMPOTENCY

--CRT_REGION_DISTRICT
DELETE [dbo].[CRT_REGION_DISTRICT]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_REGION_DISTRICT] 
)

--CRT_SERVICE_AREA
DELETE [dbo].[CRT_SERVICE_AREA]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_SERVICE_AREA] 
)

--CRT_DISTRICT
DELETE [dbo].[CRT_DISTRICT]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_DISTRICT] 
)

--CRT_REGION
DELETE [dbo].[CRT_REGION]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_REGION] 
)


--POPULATE

--CRT_REGION
INSERT INTO [dbo].[CRT_REGION] (REGION_NUMBER, REGION_NAME) VALUES (0,'Headquarters');
INSERT INTO [dbo].[CRT_REGION] (REGION_NUMBER, REGION_NAME) VALUES (1,'South Coast');
INSERT INTO [dbo].[CRT_REGION] (REGION_NUMBER, REGION_NAME) VALUES (2,'Southern Interior');
INSERT INTO [dbo].[CRT_REGION] (REGION_NUMBER, REGION_NAME) VALUES (3,'Northern');

--CRT_DISTRICT
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (1, 'Lower Mainland');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (2, 'Vancouver Island');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (3, 'Rocky Mountain');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (4, 'West Kootenay');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (5, 'Okanagan-Shuswap');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (6, 'Thompson-Nicola');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (7, 'Cariboo');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (8, 'Peace');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (9, 'Fort George');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (10, 'Bulkley-Stikine');
INSERT INTO [dbo].[CRT_DISTRICT] (DISTRICT_NUMBER, DISTRICT_NAME) VALUES (11, 'Skeena');

--CRT_REGION_DISTRICT
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =1),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =1));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =1),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =2));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =2),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =3));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =2),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =4));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =2),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =5));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =2),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =6));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =2),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =7));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =3),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =8));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =3),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =9));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =3),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =10));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =3),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =11));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =1));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =2));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =3));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =4));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =5));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =6));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =7));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =8));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =9));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =10));
INSERT INTO [dbo].[CRT_REGION_DISTRICT] (REGION_ID, DISTRICT_ID) VALUES ((SELECT REGION_ID FROM [dbo].[CRT_REGION] WHERE REGION_NUMBER =0),(SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER =11));


--CRT_SERVICE_AREA
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (1, 'South Island', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 2));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (2, 'Central Island', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 2));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (3, 'North Island', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 2));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (4, 'Howe Sound', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 1));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (5, 'Sunshine Coast', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 1));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (6, 'Lower Mainland', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 1));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (7, 'Fraser Valley', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 1));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (8, 'South Okanagan', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 5));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (9, 'Kootenay Boundary', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 4));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (10, 'Central Kootenay', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 4));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (11, 'East Kootenay', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 3));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (12, 'Selkirk', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 3));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (13, 'Okanagan-Shuswap', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 5));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (14, 'Nicola', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 6));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (15, 'Thompson', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 6));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (16, 'South Cariboo', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 7));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (17, 'Central Cariboo', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 7));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (18, 'North Cariboo', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 7));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (19, 'Fort George', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 9));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (20, 'Robson', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 9));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (21, 'South Peace', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 8));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (22, 'North Peace', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 8));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (23, 'Nechako', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 9));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (24, 'Lakes', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 10));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (25, 'Bulkley Nass', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 10));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (26, 'Skeena', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 11));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (27, 'North Coast', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 11));
INSERT INTO [dbo].[CRT_SERVICE_AREA] (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_ID) VALUES (28, 'Stikine', (SELECT DISTRICT_ID FROM [dbo].[CRT_DISTRICT] WHERE DISTRICT_NUMBER = 10));
