/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          S01_02_APP_CRT_USER_ACCESS_V1_LOV_dml            */
/* Project name:          Capital Rehabilitation Tracking Reporting       */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           Database creation script                        */
/* Created on:            2021-01-14 12:03                                */
/* ---------------------------------------------------------------------- */



USE CRT_DEV;
GO

/* Load user context variables. */
DECLARE @utcdate DATETIME = (SELECT getutcdate() AS utcdate)
DECLARE @app_guid UNIQUEIDENTIFIER = (SELECT CASE WHEN SUSER_SID() IS NOT NULL THEN SUSER_SID() ELSE (SELECT CONVERT(uniqueidentifier,STUFF(STUFF(STUFF(STUFF('B00D00A0AC0A0D0C00DD00F0D0C00000',9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-'))) END AS  app_guid)
DECLARE @app_user VARCHAR(30) = (SELECT CASE WHEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) IS NOT NULL THEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) ELSE CURRENT_USER END AS app_user)
DECLARE @app_user_dir VARCHAR(12) = (SELECT CASE WHEN LEN(SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)))>1 THEN SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)) ELSE 'WIN AUTH' END AS app_user_dir)



--IDEMPOTENCY

--CRT_ROLE_PERMISSION
DELETE [dbo].[CRT_ROLE_PERMISSION]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_ROLE_PERMISSION] 
)


--CRT_ROLE
DELETE [dbo].[CRT_ROLE]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_ROLE] 
)


--CRT_PERMISSION
DELETE [dbo].[CRT_PERMISSION]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_PERMISSION] 
)


--POPULATE

--CRT_PERMISSION
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('CODE_R', 'Code Table Read',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('CODE_W', 'Code Table Write',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('EXPORT_R', 'Export Read',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('PROJECT_R', 'Project Read',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('PROJECT_W', 'Project Write',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('ROLE_R', 'Role Read',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('ROLE_W', 'Role Write',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('USER_R', 'User Read',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_PERMISSION] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('USER_W', 'User Write',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);




--CRT_ROLE
INSERT INTO [dbo].[CRT_ROLE] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('SYSTEM_ADMIN', 'System Administrator',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('DISTRICT_ADMIN', 'District Administrator',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('MANAGER', 'Manager',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE] (NAME,DESCRIPTION,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ('READ_ONLY', 'Read Only',@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);



--CRT_ROLE_PERMISSION
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'EXPORT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'ROLE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'ROLE_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'USER_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'SYSTEM_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'USER_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'EXPORT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'ROLE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'USER_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'DISTRICT_ADMIN'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'USER_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'MANAGER'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'MANAGER'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'EXPORT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'MANAGER'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'MANAGER'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'READ_ONLY'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'READ_ONLY'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'CODE_W'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'READ_ONLY'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'PROJECT_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'READ_ONLY'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'ROLE_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
INSERT INTO [dbo].[CRT_ROLE_PERMISSION] (ROLE_ID,PERMISSION_ID,APP_CREATE_USERID,APP_CREATE_TIMESTAMP,APP_CREATE_USER_GUID,APP_LAST_UPDATE_USERID,APP_LAST_UPDATE_TIMESTAMP,APP_LAST_UPDATE_USER_GUID) VALUES ((SELECT ROLE_ID FROM [dbo].[CRT_ROLE] WHERE NAME = 'READ_ONLY'),(SELECT PERMISSION_ID FROM [dbo].[CRT_PERMISSION] WHERE NAME = 'USER_R'),@app_user,@utcdate,@app_guid,@app_user,@utcdate,@app_guid);
