USE CRT_DEV;
GO

DELETE [dbo].[CRT_CODE_LOOKUP]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].CRT_CODE_LOOKUP C
	WHERE C.CODE_SET IN ('CAP_INDX','RC','NEARST_TWN')
)



INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable-All components>40yrs', '10',NULL, '1', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable-Average components>40yrs overall', '9',NULL, '2', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable-Some components<40 yrs, but all>15yrs', '8',NULL, '3', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable-All components>15yrs', '7',NULL, '4', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable-Average components>15 yrs overall', '6',NULL, '5', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable/Expense-Some components<15yrs', '5',NULL, '6', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Capitalizable/Expense-Terminated/Deferred WIP components>15yrs', '4',NULL, '7', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Expense-All components<15yrs', '3',NULL, '8', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Expense-No additional life: original benefits only', '2',NULL, '9', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Expense-No additional life: repairs only to realize portion of original benefits', '1',NULL, '10', 'STRING');
GO 
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CAP_INDX', 'Expense- Materiality clause not met', '0',NULL, '11', 'STRING');
GO 




INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'WR Bennett Bridge', '55080',NULL, '1', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Cariboo Connector (Cap/Exp)', '55097',NULL, '2', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Lower Mainland District', '55131',NULL, '3', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Vancouver Island District', '55132',NULL, '4', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'South Coast Regional Manager, Planning and Partnerships', '55153',NULL, '5', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Rocky Mountain District', '55231',NULL, '6', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'West Kootenay District', '55232',NULL, '7', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Okanagan Shuswap District', '55233',NULL, '8', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Thompson Nicola District', '55234',NULL, '9', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Cariboo District', '55235',NULL, '10', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Capital/Expansion (Project Management)', '55254',NULL, '11', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Operations (Preservation Program)', '55255',NULL, '12', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Kickinghorse Concession', '55261',NULL, '13', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Peace District', '55331',NULL, '14', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Fort George District', '55332',NULL, '15', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Bulkley-Stikine District', '55333',NULL, '16', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Skeena District', '55334',NULL, '17', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Northern, Senior Project Manager', '55354',NULL, '18', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Northern, Reg Mgr, Operations', '55355',NULL, '19', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'HQ RC', '55711',NULL, '20', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'BMSB CSE', '55750',NULL, '21', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Geotechnical Engineering', '55860',NULL, '22', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Active Transportation', '55910',NULL, '23', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Climate Adaptation', '55911',NULL, '24', 'STRING');
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RC', 'Remote & Rural Community Access', '55912',NULL, '25', 'STRING');
GO







INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', '100 Mile House', NULL, NULL, '1', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', '150 Mile House', NULL, NULL, '2', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', '70 Mile', NULL, NULL, '3', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', '70 Mile House', NULL, NULL, '4', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Abbotsford', NULL, NULL, '5', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Adams Lake', NULL, NULL, '6', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Agassiz', NULL, NULL, '7', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Aldergrove', NULL, NULL, '8', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Alexis Creek', NULL, NULL, '9', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Anahim Lake', NULL, NULL, '10', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Armstrong', NULL, NULL, '11', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ashcroft', NULL, NULL, '12', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Atlin', NULL, NULL, '13', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Balfour', NULL, NULL, '14', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Bamfield', NULL, NULL, '15', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Barkerville', NULL, NULL, '16', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Barriere', NULL, NULL, '17', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Beaverdell', NULL, NULL, '18', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Bella Coola', NULL, NULL, '19', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Blaeberry', NULL, NULL, '20', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Blind Bay', NULL, NULL, '21', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Blue River', NULL, NULL, '22', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Boston Bar', NULL, NULL, '23', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Boswell', NULL, NULL, '24', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Bowser', NULL, NULL, '25', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Bridge Lake', NULL, NULL, '26', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Britannia Beach', NULL, NULL, '27', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burnaby, Delta, West Van', NULL, NULL, '28', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burns Lake', NULL, NULL, '29', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burns Lake/Decker Lake', NULL, NULL, '30', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burns Lake/Houston', NULL, NULL, '31', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burns Lake/Smithers', NULL, NULL, '32', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burns Lake/Telkwa/Prince George', NULL, NULL, '33', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Burton', NULL, NULL, '34', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cache Creek', NULL, NULL, '35', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Campbell River', NULL, NULL, '36', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Canal Flats', NULL, NULL, '37', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Canim Lake', NULL, NULL, '38', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Castlegar', NULL, NULL, '39', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cecil Lake', NULL, NULL, '40', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Charlie Lake', NULL, NULL, '41', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chase', NULL, NULL, '42', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chase/Qualicum', NULL, NULL, '43', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chemainus', NULL, NULL, '44', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cherry Creek', NULL, NULL, '45', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cherryville', NULL, NULL, '46', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chetwynd', NULL, NULL, '47', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chetwynd/Hudson''s Hope', NULL, NULL, '48', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chilliwack', NULL, NULL, '49', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Chilliwack/Hope', NULL, NULL, '50', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Christina Lake', NULL, NULL, '51', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Clearwater', NULL, NULL, '52', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Clearwater/Barriere', NULL, NULL, '53', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Clearwater/Merritt', NULL, NULL, '54', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Clinton', NULL, NULL, '55', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cloverdale', NULL, NULL, '56', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Coldstream', NULL, NULL, '57', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Comox', NULL, NULL, '58', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Coquitlam', NULL, NULL, '59', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Coquitlam/Delta', NULL, NULL, '60', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Courtenay', NULL, NULL, '61', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cowichan 1', NULL, NULL, '62', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cowichan Bay', NULL, NULL, '63', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Cranbrook', NULL, NULL, '64', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Creston', NULL, NULL, '65', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Crofton', NULL, NULL, '66', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Dawson Creek', NULL, NULL, '67', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Dease Lake', NULL, NULL, '68', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Delta', NULL, NULL, '69', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Delta/New Westminster', NULL, NULL, '70', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Delta/Surrey', NULL, NULL, '71', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Deroche', NULL, NULL, '72', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Donald', NULL, NULL, '73', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Duncan', NULL, NULL, '74', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Edgewood', NULL, NULL, '75', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Elkford', NULL, NULL, '76', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Elko', NULL, NULL, '77', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Enderby', NULL, NULL, '78', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Esquimalt', NULL, NULL, '79', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fairmont', NULL, NULL, '80', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fairmont Hot Springs', NULL, NULL, '81', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Falkland', NULL, NULL, '82', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fauquier', NULL, NULL, '83', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fernie', NULL, NULL, '84', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fort Nelson', NULL, NULL, '85', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fort St John', NULL, NULL, '86', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fort St. James', NULL, NULL, '87', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fort St. John', NULL, NULL, '88', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fort Steele', NULL, NULL, '89', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fraser Lake', NULL, NULL, '90', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Fruitvale', NULL, NULL, '91', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gabriola', NULL, NULL, '92', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gabriola Island', NULL, NULL, '93', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Galena Bay', NULL, NULL, '94', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ganges', NULL, NULL, '95', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gibsons', NULL, NULL, '96', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gold Bridge', NULL, NULL, '97', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gold River', NULL, NULL, '98', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Gold River/ Tahsis', NULL, NULL, '99', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Golden', NULL, NULL, '100', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Grand Forks', NULL, NULL, '101', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Greenville', NULL, NULL, '102', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hagensborg', NULL, NULL, '103', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Haig', NULL, NULL, '104', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Halfmoon Bay', NULL, NULL, '105', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hanceville', NULL, NULL, '106', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Harrison / Kent', NULL, NULL, '107', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Harrison Hot Springs', NULL, NULL, '108', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Harrogate', NULL, NULL, '109', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hazelton', NULL, NULL, '110', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hedley', NULL, NULL, '111', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Heffley Creek', NULL, NULL, '112', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hixon', NULL, NULL, '113', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Holberg', NULL, NULL, '114', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hope', NULL, NULL, '115', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hope/ Powell River', NULL, NULL, '116', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Horsefly', NULL, NULL, '117', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hosmer', NULL, NULL, '118', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Houston', NULL, NULL, '119', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Hudson''s Hope', NULL, NULL, '120', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Invermere', NULL, NULL, '121', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kaleden', NULL, NULL, '122', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kamloops', NULL, NULL, '123', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kamloops/Merritt', NULL, NULL, '124', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kaslo', NULL, NULL, '125', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kelowna', NULL, NULL, '126', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Keremeos', NULL, NULL, '127', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kimberley', NULL, NULL, '128', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kitimat', NULL, NULL, '129', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kitimat/Terrace', NULL, NULL, '130', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Kitwanga', NULL, NULL, '131', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lac la Hache', NULL, NULL, '132', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lake Country', NULL, NULL, '133', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lake Cowichan', NULL, NULL, '134', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lake Cowichan and Sidney', NULL, NULL, '135', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Langford', NULL, NULL, '136', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Langley', NULL, NULL, '137', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Langley/ Maple Ridge', NULL, NULL, '138', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Likely', NULL, NULL, '139', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lillooet', NULL, NULL, '140', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lillooett', NULL, NULL, '141', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lions Bay', NULL, NULL, '142', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Little Fort', NULL, NULL, '143', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Logan Lake', NULL, NULL, '144', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lone Butte', NULL, NULL, '145', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lumby', NULL, NULL, '146', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Lytton', NULL, NULL, '147', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mackenzie', NULL, NULL, '148', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Maple Ridge', NULL, NULL, '149', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Maple Ridge/Mission', NULL, NULL, '150', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Maple Ridge/Pitt Meadows', NULL, NULL, '151', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mara', NULL, NULL, '152', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Masset/Port Clements', NULL, NULL, '153', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'McBride', NULL, NULL, '154', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'McBride/Valemount', NULL, NULL, '155', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'McClure', NULL, NULL, '156', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Merritt', NULL, NULL, '157', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Merritt &Kelowna', NULL, NULL, '158', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mill Bay', NULL, NULL, '159', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mill Bay/Langford', NULL, NULL, '160', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'misc', NULL, NULL, '161', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mission', NULL, NULL, '162', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mission/Abbotsford', NULL, NULL, '163', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Monte Lake', NULL, NULL, '164', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Montrose', NULL, NULL, '165', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Mount Currie', NULL, NULL, '166', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Moyie', NULL, NULL, '167', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'n/a', NULL, NULL, '168', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nakusp', NULL, NULL, '169', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nanaimo', NULL, NULL, '170', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nanaimo/ Courtenay', NULL, NULL, '171', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nanoose Bay', NULL, NULL, '172', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Naramata', NULL, NULL, '173', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nearest Town', NULL, NULL, '174', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nelson', NULL, NULL, '175', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Nelson/Castlegar', NULL, NULL, '176', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'New Aiyansh', NULL, NULL, '177', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'New Denver', NULL, NULL, '178', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'New Westminster', NULL, NULL, '179', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'New Westminster/Surrey', NULL, NULL, '180', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'North Van, Vancouver, Richmond', NULL, NULL, '181', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'North Vancouver', NULL, NULL, '182', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Okanagan Falls', NULL, NULL, '183', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Oliver', NULL, NULL, '184', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ootischenia', NULL, NULL, '185', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Osoyoos', NULL, NULL, '186', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Oyama', NULL, NULL, '187', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Panorama', NULL, NULL, '188', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Parksville', NULL, NULL, '189', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Peachland', NULL, NULL, '190', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Pemberton', NULL, NULL, '191', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Pender Harbor', NULL, NULL, '192', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Penticton', NULL, NULL, '193', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Pitt Meadows', NULL, NULL, '194', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port Alberni', NULL, NULL, '195', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port Alice', NULL, NULL, '196', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port Coquitlam', NULL, NULL, '197', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port McNeill', NULL, NULL, '199', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port Mellon', NULL, NULL, '200', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Port Renfrew', NULL, NULL, '201', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Pouce Coupe', NULL, NULL, '202', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Powell River', NULL, NULL, '203', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Prince George', NULL, NULL, '204', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Prince George/Fort St. James', NULL, NULL, '205', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Prince George/Smithers', NULL, NULL, '206', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Prince Geroge', NULL, NULL, '207', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Prince Rupert', NULL, NULL, '208', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Princeton', NULL, NULL, '209', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Pritchard', NULL, NULL, '210', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Quadra Island', NULL, NULL, '211', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Qualicum', NULL, NULL, '212', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Queen Charlotte City', NULL, NULL, '213', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Quesnel', NULL, NULL, '214', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Quilchena', NULL, NULL, '215', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Radium Hot Springs', NULL, NULL, '216', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Revelstoke', NULL, NULL, '217', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Revelstoke/Golden', NULL, NULL, '218', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Richmond', NULL, NULL, '219', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Richmond/Delta', NULL, NULL, '220', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Riske Creek', NULL, NULL, '221', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Roberts Creek', NULL, NULL, '222', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Rock Creek', NULL, NULL, '223', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Rose Lake', NULL, NULL, '224', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Rossland', NULL, NULL, '225', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ruskin', NULL, NULL, '226', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Rutland', NULL, NULL, '227', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Saanich', NULL, NULL, '228', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Saanich/Duncan', NULL, NULL, '229', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Salmo', NULL, NULL, '230', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Salmon Arm', NULL, NULL, '231', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Savary Island', NULL, NULL, '232', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Savona', NULL, NULL, '233', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sayward', NULL, NULL, '234', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sechelt', NULL, NULL, '235', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Seton Portage', NULL, NULL, '236', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Shawnigan Lake', NULL, NULL, '237', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sicamous', NULL, NULL, '238', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sidney', NULL, NULL, '239', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Silverton', NULL, NULL, '240', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Skookumchuck', NULL, NULL, '241', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Slocan', NULL, NULL, '242', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Smithers', NULL, NULL, '243', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sooke', NULL, NULL, '244', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sorrento', NULL, NULL, '245', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'South Slocan', NULL, NULL, '246', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Spallumcheen', NULL, NULL, '247', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Sparwood', NULL, NULL, '248', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Spences Bridge', NULL, NULL, '249', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Spuzzum', NULL, NULL, '250', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Squamish', NULL, NULL, '251', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Squilax', NULL, NULL, '252', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Stewart', NULL, NULL, '253', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Stewrt', NULL, NULL, '254', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Summerland', NULL, NULL, '255', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Surrey', NULL, NULL, '256', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Surrey, Langley', NULL, NULL, '258', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Surrey/Cloverdale', NULL, NULL, '259', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Surrey/Richmond', NULL, NULL, '260', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tahsis', NULL, NULL, '261', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tappen', NULL, NULL, '262', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tatla Lake', NULL, NULL, '263', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Taylor', NULL, NULL, '264', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Telkwa', NULL, NULL, '265', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Terrace', NULL, NULL, '266', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tte Jaune Cache', NULL, NULL, '267', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tlell', NULL, NULL, '268', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tofino', NULL, NULL, '269', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Topley', NULL, NULL, '270', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Trail', NULL, NULL, '271', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Trail/Rossland', NULL, NULL, '272', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Tumbler Ridge', NULL, NULL, '273', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ucluelet', NULL, NULL, '274', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Union Bay', NULL, NULL, '275', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Unknown', NULL, NULL, '276', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Valemount', NULL, NULL, '277', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Valemount/Blue River', NULL, NULL, '278', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Valmount', NULL, NULL, '279', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vancouver', NULL, NULL, '280', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vancouver/Richmond', NULL, NULL, '282', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vancouver/West Vancouver', NULL, NULL, '283', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vancouver/Whistler', NULL, NULL, '284', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vanderhoof', NULL, NULL, '285', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vanderhoof/Fraser Lake/Fort St James', NULL, NULL, '286', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Various', NULL, NULL, '287', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vavenby', NULL, NULL, '289', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Vernon', NULL, NULL, '290', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Victoria', NULL, NULL, '291', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'View Royal', NULL, NULL, '292', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Walhachin', NULL, NULL, '293', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Wardner', NULL, NULL, '294', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Warfield', NULL, NULL, '295', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'West Kelowna', NULL, NULL, '296', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'West Kelowna/Kelowna', NULL, NULL, '297', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'West Vancouver', NULL, NULL, '298', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Westbank', NULL, NULL, '299', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Westwold', NULL, NULL, '300', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Whistler', NULL, NULL, '301', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Whistler/Pemberton', NULL, NULL, '302', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'williams Lake', NULL, NULL, '303', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Windermere', NULL, NULL, '305', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Winlaw', NULL, NULL, '306', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Witset', NULL, NULL, '307', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Woss', NULL, NULL, '308', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Yahk', NULL, NULL, '309', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Yale', NULL, NULL, '310', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Ymir', NULL, NULL, '311', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Youbou', NULL, NULL, '312', NULL);
GO
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('NEARST_TWN', 'Zeballos', NULL, NULL, '313', NULL);
GO
