
USE CRT_DEV;
GO

DELETE [dbo].[CRT_CODE_LOOKUP]
WHERE EXISTS
(
	SELECT *
FROM [dbo].[CRT_CODE_LOOKUP] C
WHERE C.CODE_SET IN ('PHASE','FISCAL_YEAR','QUANTITY', 'ACCOMPLISHMENT','CONTRACTOR','FORECAST_TYPE')
)


INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Plan', 'P', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Engineer', 'E', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Construct', 'C', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Other', 'O', NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Shelf Ready', 'S', NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Complete', 'F', NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PHASE', 'Unknown', 'U', NULL, 7, 'STRING');


INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2010/2011', '', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2011/2012', '', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2012/2013', '', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2013/2014', '', NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2014/2015', '', NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2015/2016', '', NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2016/2017', '', NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2017/2018', '', NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2018/2019', '', NULL, 9, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2019/2020', '', NULL, 10, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2020/2021', '', NULL, 11, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2021/2022', '', NULL, 12, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2022/2023', '', NULL, 13, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2023/2024', '', NULL, 14, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2024/2025', '', NULL, 15, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2025/2026', '', NULL, 16, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2026/2027', '', NULL, 17, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', '2027/2028', '', NULL, 18, 'STRING');

INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('QUANTITY', 'Asphalt Mix  (tonnes)', '', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('QUANTITY', 'Hwy - GAS/Seal Coat  (m2)', '', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('QUANTITY', 'Hwy - GAS/Seal Coat  (m2)', '', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('QUANTITY', 'Hot in Place  (m2)', '', NULL, 4, 'STRING');

INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Active Transportation Project ', '', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Bridge Installed, New  (each)', '', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Bridge Rehabbed  (each)', '', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Bridge Replaced  (each)', '', NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Bridge Resurfaced  (each)', '', NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Concrete Overlay  (m2)', '', NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Culvert <3m  (lineal m)', '', NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Culvert 3m+ Rehabbed  (each)', '', NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Culvert 3m+ Replaced  (each)', '', NULL, 9, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Durable Pavement Marking  (m2)', '', NULL, 10, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Durable Pavement Marking  (linear m)', '', NULL, 11, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Fencing Rehabbed  - Shoulder (linear m)', '', NULL, 12, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'First Time HS  (lane km)', '', NULL, 13, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Gravelled roads  (km)', '', NULL, 15, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Guardrail  (linear m)', '', NULL, 16, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'High Friction Surface  (m2)', '', NULL, 17, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Hwy - Asphalt  (lane km)', '', NULL, 18, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Hwy - GAS/Seal Coat  (lane km)', '', NULL, 19, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Hwy - HIP  (lane km)', '', NULL, 20, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Intersection Improved  (each)', '', NULL, 21, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Jobs Created (each)', '', NULL, 22, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'New Fencing  (linear m)', '', NULL, 23, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'New Guardrail  (linear m)', '', NULL, 24, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Passing Lanes  (km)', '', NULL, 25, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'RAP  (lane km)', '', NULL, 26, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'RIP RAP  (m3)', '', NULL, 27, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Road strengthening  (m2)', '', NULL, 28, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Rumble Strip - Shoulder (km)', '', NULL, 29, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Rumble Strip - Centerline (km)', '', NULL, 30, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Seismic Upgrade  (each)', '', NULL, 31, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Shoulder Improvements  - CenterLine (km)', '', NULL, 32, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Side - Asphalt  (lane km)', '', NULL, 33, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Side - GAS/Seal Coat  (lane km)', '', NULL, 34, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Side - HIP  (lane km)', '', NULL, 35, 'STRING');

INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', '647354 BC Ltd', '', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', '672462 BC', '', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'A.L. Sims', '', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Adventure', '', NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Alpine', '', NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'ARC', '', NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Ardy Rigging', '', NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Arrowsmith', '', NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Axis Mountain Technical Inc.', '', NULL, 9, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'BA Blacktop', '', NULL, 10, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'BA Dawson', '', NULL, 11, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'BD Hall', '', NULL, 12, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Bear Creek', '', NULL, 13, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Belvedere', '', NULL, 14, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'BG Macdonald', '', NULL, 15, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Borrow Ent.', '', NULL, 16, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Brinkman', '', NULL, 17, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Brocor Construction Ltd.', '', NULL, 18, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'C & C Road Maintenance Ltd.', '', NULL, 19, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Cantex-Okan', '', NULL, 20, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'CEWE Infrastructure Ltd.', '', NULL, 21, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Chimera', '', NULL, 22, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Copcan', '', NULL, 23, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Coq. Ridge', '', NULL, 24, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Cortez Const.', '', NULL, 25, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Crown Contracting Limited', '', NULL, 26, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Dawson', '', NULL, 27, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Dunwell Innov.', '', NULL, 28, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'EAC', '', NULL, 29, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Eiffage Innovative Canada Inc.', '', NULL, 30, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Enviro-Ex Contracting Ltd.', '', NULL, 31, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Extreme Exc.', '', NULL, 32, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Forbes Industrial Contractors Ltd.', '', NULL, 33, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Formula Contracts Ltd.', '', NULL, 34, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Fortitude', '', NULL, 35, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Garcia & Sons', '', NULL, 36, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Giffels West.', '', NULL, 37, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Golden Base', '', NULL, 38, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Green Roads', '', NULL, 39, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Heavy Metal', '', NULL, 40, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'IDL Projects', '', NULL, 41, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Infinite Road Markings', '', NULL, 42, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Interoute', '', NULL, 43, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Jack Cewe', '', NULL, 44, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Jacob Bros.', '', NULL, 45, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Jakes', '', NULL, 46, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Jamac Painting & Sandblasting Ltd.', '', NULL, 47, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Keller Foundations', '', NULL, 48, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Key-West Asphalt (333)', '', NULL, 49, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Kiewit', '', NULL, 50, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Kingston', '', NULL, 51, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Kon Kast', '', NULL, 52, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Lafarge', '', NULL, 53, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'LaFrentz', '', NULL, 54, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'LB Paving', '', NULL, 55, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Ledcor Highways Ltd.', '', NULL, 56, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Line West', '', NULL, 57, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'LNB Const.', '', NULL, 58, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Luxton Construction Inc.', '', NULL, 59, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'M. Johnston', '', NULL, 60, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Maglio', '', NULL, 61, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Mainroad', '', NULL, 62, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'MB Const. Ltd.', '', NULL, 63, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Milner Group', '', NULL, 64, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'MRC Total Build LP', '', NULL, 65, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'MTF Enterp.', '', NULL, 66, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Mtn. Rock', '', NULL, 67, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'NBC Contracting Inc.', '', NULL, 68, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'NBC Contracting Inc.', '', NULL, 69, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Neds Creek', '', NULL, 70, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'North Country Maintenance Inc.', '', NULL, 71, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'North Gate', '', NULL, 72, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'OK Agg', '', NULL, 73, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'OK Industries', '', NULL, 74, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Online Constructors Ltd.', '', NULL, 75, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Pacific Industrial & Marine Ltd.', '', NULL, 76, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Peters Bros.', '', NULL, 77, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Pittman', '', NULL, 78, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'QM LP', '', NULL, 79, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Quesnel Pav', '', NULL, 80, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'R355 Ent. Ltd.', '', NULL, 81, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Ruskin Construction Ltd.', '', NULL, 82, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'S. Young Enterprises Ltd.', '', NULL, 83, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'SCV Contract.', '', NULL, 84, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Sealtec', '', NULL, 85, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Seismic 2000', '', NULL, 86, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Sorenson Excavating Ltd.', '', NULL, 87, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Sparker', '', NULL, 88, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Stuart Olson Construction Ltd.', '', NULL, 89, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Superior', '', NULL, 90, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Surespan', '', NULL, 91, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Sutton', '', NULL, 92, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Terus Construction Ltd.', '', NULL, 93, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Timbro', '', NULL, 94, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'TYBO', '', NULL, 95, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Uplands', '', NULL, 96, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Wacor', '', NULL, 97, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'West Bridge', '', NULL, 98, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Western Watershed Designs Inc.', '', NULL, 99, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'White Bear Ind.', '', NULL, 100, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CONTRACTOR', 'Windley', '', NULL, 101, 'STRING');

INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Allocation', '', NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Priority', '', NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Over Program', '', NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Bridge Uplift', '', NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Partner $', '', NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'Notional', '', NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'DFAA', '', NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP]
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FORECAST_TYPE', 'BCTFA', '', NULL, 9, 'STRING');
