
/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 12.1.0                     */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          S04_02_APP_CRT_V1.dez                           */
/* Project name:          Capital Rehabilitation Tracking Reporting       */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           DML database script                           */
/* Created on:            2021-02-25 17:38                                */
/* ---------------------------------------------------------------------- */

/*

*/

DELETE [dbo].[CRT_CODE_LOOKUP]
WHERE EXISTS
(
	SELECT *
	FROM  [dbo].[CRT_CODE_LOOKUP] C
	WHERE C.CODE_SET IN ('ECONOMIC_REGION','ELECTORAL_DISTRICT','HIGHWAY')
)


INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Province', '',NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Lower Mainland', '',NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Thompson Okanagan', '',NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Cariboo', '',NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Kootenays', '',NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'Vancouver Island', '',NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'North Central', '',NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'North West', '',NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ECONOMIC_REGION', 'North East', '',NULL, 9, 'STRING');




INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cariboo North', '',NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Chilliwack', '',NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Chilliwack-Hope', '',NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Columbia River-Revelstoke', '',NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Comox Valley', '',NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Coquitlam-Burke Mountain', '',NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Coquitlam-Maillardville', '',NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cowichan Valley', '',NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nelson-Creston', '',NULL, 9, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'New Westminster', '',NULL, 10, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Coast', '',NULL, 11, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Island', '',NULL, 12, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Vancouver-Lonsdale', '',NULL, 13, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Vancouver-Seymour', '',NULL, 14, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford-Mission', '',NULL, 15, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford South', '',NULL, 16, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford West', '',NULL, 17, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Alberni-Pacific Rim', '',NULL, 18, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Boundary-Similkameen', '',NULL, 19, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby-Deer Lake', '',NULL, 20, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby-Edmonds', '',NULL, 21, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby-Lougheed', '',NULL, 22, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby North', '',NULL, 23, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cariboo-Chilcotin', '',NULL, 24, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Delta North', '',NULL, 25, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Delta South', '',NULL, 26, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Esquimalt-Royal Roads', '',NULL, 27, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Fort Langley-Aldergrove', '',NULL, 28, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Fraser-Nicola', '',NULL, 29, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Juan de Fuca', '',NULL, 30, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kamloops-North Thompson', '',NULL, 31, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kamloops-South Thompson', '',NULL, 32, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kelowna-Lake Country', '',NULL, 33, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kelowna-Mission', '',NULL, 34, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kootenay East', '',NULL, 35, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kootenay West', '',NULL, 36, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Langley', '',NULL, 37, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Maple Ridge-Mission', '',NULL, 38, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Maple Ridge-Pitt Meadows', '',NULL, 39, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nanaimo', '',NULL, 40, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nanaimo-North Cowichan', '',NULL, 41, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nechako Lakes', '',NULL, 42, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Oak Bay-Gordon Head', '',NULL, 43, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Parksville-Qualicum', '',NULL, 44, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Peace River North', '',NULL, 45, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Peace River South', '',NULL, 46, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Penticton', '',NULL, 47, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Port Coquitlam', '',NULL, 48, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Port Moody-Coquitlam', '',NULL, 49, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Powell River-Sunshine Coast', '',NULL, 50, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Prince George-Mackenzie', '',NULL, 51, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Prince George-Valemount', '',NULL, 52, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond Centre', '',NULL, 53, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond East', '',NULL, 54, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond-Steveston', '',NULL, 55, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Saanich North and the Islands', '',NULL, 56, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Saanich South', '',NULL, 57, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Shuswap', '',NULL, 58, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Skeena', '',NULL, 59, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Stikine', '',NULL, 60, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Cloverdale', '',NULL, 61, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Fleetwood', '',NULL, 62, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Green Timbers', '',NULL, 63, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Newton', '',NULL, 64, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Panorama', '',NULL, 65, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Tynehead', '',NULL, 66, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-Whalley', '',NULL, 67, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey-White Rock', '',NULL, 68, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Fairview', '',NULL, 69, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-False Creek', '',NULL, 70, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Fraserview', '',NULL, 71, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Hastings', '',NULL, 72, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Kensington', '',NULL, 73, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Kingsway', '',NULL, 74, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Langara', '',NULL, 75, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Mount Pleasant', '',NULL, 76, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Point Grey', '',NULL, 77, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-Quilchena', '',NULL, 78, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver-West End', '',NULL, 79, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vernon-Monashee', '',NULL, 80, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Victoria-Beacon Hill', '',NULL, 81, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Victoria-Swan Lake', '',NULL, 82, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'West Vancouver-Capilano', '',NULL, 83, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'West Vancouver-Sea to Sky', '',NULL, 84, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Westside-Kelowna', '',NULL, 85, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Unallocated', '',NULL, 86, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford - Mission', '',NULL, 87, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford South', '',NULL, 88, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Abbotsford West', '',NULL, 89, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Boundary - Similkameen', '',NULL, 90, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby - Deer Lake', '',NULL, 91, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby - Edmonds', '',NULL, 92, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby - Lougheed', '',NULL, 93, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Burnaby North', '',NULL, 94, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cariboo - Chilcotin', '',NULL, 95, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cariboo North', '',NULL, 96, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Chilliwack', '',NULL, 97, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Chilliwack - Kent', '',NULL, 98, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Columbia River - Revelstoke', '',NULL, 99, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Coquitlam - Burke Mountain', '',NULL, 100, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Coquitlam - Mallairdville', '',NULL, 101, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Courtenay-Comox', '',NULL, 102, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Cowichan Valley', '',NULL, 103, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Delta North', '',NULL, 104, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Delta South', '',NULL, 105, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Esquimalt - Metchosin', '',NULL, 106, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Fraser - Nicola', '',NULL, 107, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kamloops - North Thompson', '',NULL, 108, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kamloops - South Thompson', '',NULL, 109, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kelowna - Lake Country', '',NULL, 110, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kelowna - Mission', '',NULL, 111, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kelowna West', '',NULL, 112, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kootenay East', '',NULL, 113, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Kootenay West', '',NULL, 114, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Langford - Juan De Fuca', '',NULL, 115, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Langley', '',NULL, 116, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Langley East', '',NULL, 117, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Maple Ridge -Mission', '',NULL, 118, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Maple Ridge - Pitt Meadows', '',NULL, 119, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Mid Island - Pacific Rim', '',NULL, 120, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nanaimo', '',NULL, 121, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nanaimo - North Cowichan', '',NULL, 122, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nechako Lakes', '',NULL, 123, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Nelson-Creston', '',NULL, 124, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'New Westminster', '',NULL, 125, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Coast', '',NULL, 126, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Island', '',NULL, 127, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Vancouver - Lonsdale', '',NULL, 128, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'North Vancouver - Seymour', '',NULL, 129, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Oak Bay - Gordon Head', '',NULL, 130, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Parksville - Qualicum', '',NULL, 131, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Peace River North', '',NULL, 132, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Peace River South', '',NULL, 133, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Penticton', '',NULL, 134, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Port Coquitlam', '',NULL, 135, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Port Moody - Coquitlam', '',NULL, 136, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Powell River - Sunshine Coast', '',NULL, 137, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Prince George - Mackenzie', '',NULL, 138, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Prince George - Valemount', '',NULL, 139, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond - North Centre', '',NULL, 140, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond - Steveston', '',NULL, 141, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond- Queensborough', '',NULL, 142, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Richmond South Centre', '',NULL, 143, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Saanich North and the Islands', '',NULL, 144, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Saanich South', '',NULL, 145, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Shuswap', '',NULL, 146, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Skeena', '',NULL, 147, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Stikine', '',NULL, 148, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Cloverdale', '',NULL, 149, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Fleetwood', '',NULL, 150, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Green Timbers', '',NULL, 151, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Guilford', '',NULL, 152, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Newton', '',NULL, 153, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Panorama', '',NULL, 154, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - Whalley', '',NULL, 155, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey - White Rock', '',NULL, 156, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Surrey South', '',NULL, 157, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Fairview', '',NULL, 158, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - False Creek', '',NULL, 159, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Fraserview', '',NULL, 160, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Hastings', '',NULL, 161, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Kensington', '',NULL, 162, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Kingsway', '',NULL, 163, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Langara', '',NULL, 164, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Mount Pleasant', '',NULL, 165, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Point Grey', '',NULL, 166, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - Quilchena', '',NULL, 167, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vancouver - West End', '',NULL, 168, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Vernon - Monashee', '',NULL, 169, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Victoria - Beacon Hill', '',NULL, 170, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Victoria - Swan Lake', '',NULL, 171, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'West Vancouver - Capilano', '',NULL, 172, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'West Vancouver - Sea to Sky', '',NULL, 173, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('ELECTORAL_DISTRICT', 'Unallocated', '',NULL, 174, 'STRING');



INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 1', '1',NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 2', '2',NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 3', '3',NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 4', '4',NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 5', '5',NULL, 5, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 6', '6',NULL, 6, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 7', '7',NULL, 7, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 8', '8',NULL, 8, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 9', '9',NULL, 9, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 10', '10',NULL, 10, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 11', '11',NULL, 11, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 12', '12',NULL, 12, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 13', '13',NULL, 13, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 14', '14',NULL, 14, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 15', '15',NULL, 15, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 16', '16',NULL, 16, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 17', '17',NULL, 17, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 18', '18',NULL, 18, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 19', '19',NULL, 19, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 20', '20',NULL, 20, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 21', '21',NULL, 21, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 22', '22',NULL, 22, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 23', '23',NULL, 23, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 24', '24',NULL, 24, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 26', '26',NULL, 25, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 27', '27',NULL, 26, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 28', '28',NULL, 27, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 29', '29',NULL, 28, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 30', '30',NULL, 29, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 31', '31',NULL, 30, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 33', '33',NULL, 31, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 35', '35',NULL, 32, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 37', '37',NULL, 33, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 39', '39',NULL, 34, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 41', '41',NULL, 35, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 43', '43',NULL, 36, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 49', '49',NULL, 37, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 52', '52',NULL, 38, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 77', '77',NULL, 39, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 91', '91',NULL, 40, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 93', '93',NULL, 41, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 95', '95',NULL, 42, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 97', '97',NULL, 43, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 99', '99',NULL, 44, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 101', '101',NULL, 45, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 113', '113',NULL, 46, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 118', '118',NULL, 47, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 395', '395',NULL, 48, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'All Hwys', 'ALL',NULL, 49, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 19A', '19A',NULL, 50, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 1A', '1A',NULL, 51, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 22A', '22A',NULL, 52, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 31A', '31A',NULL, 53, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 37A', '37A',NULL, 54, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 3A', '3A',NULL, 55, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 3B', '3B',NULL, 56, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 5A', '5A',NULL, 57, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 7B', '7B',NULL, 58, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 91A', '91A',NULL, 59, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 95A', '95A',NULL, 60, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 97A', '97A',NULL, 61, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 97B', '97B',NULL, 62, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 97C', '97C',NULL, 63, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 97D', '97D',NULL, 64, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 17A', '17A',NULL, 65, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('HIGHWAY', 'Hwy 62', '62',NULL, 66, 'STRING');





INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RATIO_RECORD_TYPE', 'Electoral District', '',NULL, 1, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RATIO_RECORD_TYPE', 'Economic Region', '',NULL, 2, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RATIO_RECORD_TYPE', 'Highway', '',NULL, 3, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RATIO_RECORD_TYPE', 'District', '',NULL, 4, 'STRING');
INSERT INTO [dbo].[CRT_CODE_LOOKUP] (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('RATIO_RECORD_TYPE', 'Service Area', '',NULL, 5, 'STRING');
