USE [CRT_DEV];
GO

INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Accomplishment', 'ACCOMPLISHMENT',NULL, 1, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Capital Index', 'CAP_INDX',NULL, 2, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Contractor', 'CONTRACTOR',NULL, 3, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Economic Region', 'ECONOMIC_REGION',NULL, 4, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Electoral District', 'ELECTORAL_DISTRICT',NULL, 5, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Fiscal Year', 'FISCAL_YEAR',NULL, 6, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Funding Type', 'FUNDING_TYPE',NULL, 7, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Highway', 'HIGHWAY',NULL, 8, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Nearest Town', 'NEARST_TWN',NULL, 9, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Phase', 'PHASE',NULL, 10, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Program', 'PROGRAM',NULL, 11, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Quantity', 'QUANTITY',NULL, 12, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'RC Number', 'RC',NULL, 13, 'STRING');
INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT) VALUES ('CODE_SET_LOOKUP', 'Service Line', 'SERVICE_LINE',NULL, 14, 'STRING');