USE CRT_DEV;
GO

--DDL TO CREATE ELEMENT TEMPORARY TABLE
DROP SEQUENCE IF EXISTS [dbo].[CRT_ELEMENT_TMP_ID_SEQ]
CREATE SEQUENCE [dbo].[CRT_ELEMENT_TMP_ID_SEQ]
  AS BIGINT 
  START WITH 1
  INCREMENT BY 1 
  MINVALUE  1
  MAXVALUE  99999999999 
  NO CYCLE
  CACHE 50
GO


DROP TABLE IF EXISTS CRT_ELEMENT_TMP

CREATE TABLE [dbo].[CRT_ELEMENT_TMP]
(
  [ELEMENT_ID] NUMERIC(9),
  [CODE] VARCHAR(40),
  [DESCRIPTION] VARCHAR(255),
  [COMMENT] VARCHAR(2000),
  [PROGRAM] VARCHAR(255),
  [PROGRAM_CATEGORY] VARCHAR(255),
  [SERVICE_LINE] VARCHAR(255),
  [IS_ACTIVE] BIT
);

GO






INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('At', 'Transportation Policy & Programs - Active Transportation', 'Stimulus', 'Stimulus', '60655', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bb', 'Bike BC', 'Capital  ', 'Grants - Bike BC', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bc', 'Bridge Coatings', 'Preservation', 'HRP-Bridges', '62175', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bd', 'Bridge Deck Resurfacing', 'Preservation', 'HRP-Bridges', '62560', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bi', 'Bridge Inspections', 'Preservation', 'HRP-Bridges', '62176', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bj', 'Bridge Joints', 'Preservation', 'HRP-Bridges', '62175', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bl', 'Lifeline Structures', 'Preservation', 'HRP-Bridges', '62630', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bm', 'Bridge Repair and Maintenance', 'Preservation', 'HRP-Bridges', '62175', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bn', 'Bridge Replacement', 'Preservation', 'HRP-Bridges', '62610', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Br', 'Bridge Rehabilitation', 'Preservation', 'HRP-Bridges', '62630', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Bs', 'Bridge Scour  ', 'Preservation', 'HRP-Bridges', '62630', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ca', 'Climate Adaptation', 'Stimulus', 'Stimulus', '61610', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('CC', 'Cariboo Connector', 'Capital  ', 'Cariboo Connector', '62120', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ce', 'Community Safety Enhancement Program', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Cn', 'Program Contingency', 'Preservation', 'Unclassified', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Cv', 'Community Volunteer', 'Preservation', 'Unclassified', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Dd', 'Emergency Contingency', 'Unclassified', 'Unclassified', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Dr', 'Durable Pavement Markings', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ex', 'Expansion - General', 'Capital  ', 'CapitalEx-Gen', '62120', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Fe', 'Wildlife Fencing', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Gr', 'Guardrail', 'Preservation', 'RSIP', '62530', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Hf', 'High Friction Surface Treatment', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ho', 'Natural Gas', 'Preservation', 'Natural Gas', '62590', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('If', 'Inland Ferries', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Lr', 'Rest Areas', 'Capital  ', 'CapitalEx-Gen', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Mo', 'Re-Profiled Projects', 'Unclassified', 'Unclassified', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Not Applicable', 'Blank Element', 'Unclassified', 'Unclassified', '0', 'FALSE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ns', 'Ehhanced Sideroad - Surfacing', 'Preservation', 'SRIP', '62163', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Nu', 'Enhanced Sideroad - Upgrades', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('P3', 'P3', 'Preservation', 'HRP - P3', '62650', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Pts', 'Painting - Transverse Sideroads', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Qb', 'Seismic Upgrade', 'Preservation', 'HRP-Bridges', '62620', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Rb', 'Road Minor Betterments Hwys', 'Preservation', 'HRP-Surfacing', '62545', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Rn', '1st Time Hard Surfacing', 'Preservation', 'HRP-Surfacing', '62570', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Rr', 'Remote & Rural Community Access', 'Stimulus', 'Stimulus', '61610', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Rs', 'Road Resurfacing', 'Preservation', 'HRP-Surfacing', '62535', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sa', 'Avalanche Weather Network & Mitigation', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sc', 'Fish Culverts', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sd', 'Noxious Weeds', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sf', 'Wildlife Accident Record Sys', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sg', 'Signs', 'Preservation', 'RSIP', '62179', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sh', 'Capital Maintenance', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Si', 'Enhanced Bridge Inspections', 'Preservation', 'HRP-Bridges', '62176', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sm', 'CHRIS & HPMA & BMIS', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sn', 'Electrical Installation', 'Preservation', 'SRIP', '62171', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('So', 'Recoverable Rehab Operations', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sp', 'Safety Program', 'Preservation', 'RSIP', '62520', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sr', 'Sideroad Resurfacing', 'Preservation', 'SRIP', '62163', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ss', 'Seasonal Strength Loss Contracts', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('St', 'Traffic Data Program', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Su', 'Sideroad Upgrading', 'Preservation', 'SRIP', '62169', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sw', 'Slides and Washouts', 'Preservation', 'HRP - SW', '62181', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sw-DFAA', 'Slides and Washouts under a DFAA claim', 'Unclassified', 'Unclassified-DFAA', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Sx', 'Railway Crossings', 'Preservation', 'RSIP', '0', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Tc', 'Transit - Capital', 'Transit', 'Transit-Cap', '64555', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Ts', 'Transit - Operating', 'Transit', 'Transit-Ops', '64553', 'TRUE')
INSERT  INTO  CRT_ELEMENT_TMP
  (CODE, DESCRIPTION,PROGRAM_CATEGORY,PROGRAM,SERVICE_LINE,IS_ACTIVE)
VALUES
  ('Unknown', 'Unknown', 'Unclassified', 'Unclassified', '0', 'FALSE');

GO

--Update CRT_ELEMENT with the TMP table

UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'At' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'At' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'At' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'At' ) ,       DISPLAY_ORDER = 1,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'At'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bb' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bb' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bb' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bb' ) ,       DISPLAY_ORDER = 2,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bb'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bc' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bc' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bc' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bc' ) ,       DISPLAY_ORDER = 3,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bc'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bd' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bd' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bd' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bd' ) ,       DISPLAY_ORDER = 4,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bd'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bi' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bi' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bi' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bi' ) ,       DISPLAY_ORDER = 5,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bi'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bj' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bj' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bj' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bj' ) ,       DISPLAY_ORDER = 6,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bj'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bl' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bl' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bl' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bl' ) ,       DISPLAY_ORDER = 7,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bl'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bm' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bm' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bm' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bm' ) ,       DISPLAY_ORDER = 8,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bm'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bn' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bn' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bn' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bn' ) ,       DISPLAY_ORDER = 9,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bn'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Br' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Br' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Br' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Br' ) ,       DISPLAY_ORDER = 10,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Br'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Bs' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Bs' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Bs' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Bs' ) ,       DISPLAY_ORDER = 11,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Bs'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ca' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ca' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ca' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ca' ) ,       DISPLAY_ORDER = 12,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ca'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'CC' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'CC' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'CC' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'CC' ) ,       DISPLAY_ORDER = 13,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'CC'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ce' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ce' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ce' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ce' ) ,       DISPLAY_ORDER = 14,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ce'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Cn' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Cn' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Cn' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Cn' ) ,       DISPLAY_ORDER = 15,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Cn'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Cv' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Cv' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Cv' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Cv' ) ,       DISPLAY_ORDER = 16,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Cv'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Dd' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Dd' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Dd' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Dd' ) ,       DISPLAY_ORDER = 17,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Dd'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Dr' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Dr' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Dr' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Dr' ) ,       DISPLAY_ORDER = 18,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Dr'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ex' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ex' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ex' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ex' ) ,       DISPLAY_ORDER = 19,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ex'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Fe' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Fe' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Fe' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Fe' ) ,       DISPLAY_ORDER = 20,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Fe'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Gr' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Gr' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Gr' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Gr' ) ,       DISPLAY_ORDER = 21,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Gr'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Hf' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Hf' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Hf' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Hf' ) ,       DISPLAY_ORDER = 22,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Hf'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ho' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ho' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ho' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ho' ) ,       DISPLAY_ORDER = 23,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ho'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'If' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'If' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'If' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'If' ) ,       DISPLAY_ORDER = 24,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'If'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Lr' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Lr' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Lr' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Lr' ) ,       DISPLAY_ORDER = 25,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Lr'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Mo' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Mo' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Mo' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Mo' ) ,       DISPLAY_ORDER = 26,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Mo'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Not Applicable' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Not Applicable' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Not Applicable' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Not Applicable' ) ,       DISPLAY_ORDER = 27,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Not Applicable'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ns' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ns' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ns' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ns' ) ,       DISPLAY_ORDER = 28,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ns'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Nu' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Nu' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Nu' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Nu' ) ,       DISPLAY_ORDER = 29,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Nu'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'P3' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'P3' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'P3' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'P3' ) ,       DISPLAY_ORDER = 30,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'P3'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Pts' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Pts' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Pts' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Pts' ) ,       DISPLAY_ORDER = 31,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Pts'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Qb' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Qb' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Qb' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Qb' ) ,       DISPLAY_ORDER = 32,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Qb'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Rb' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Rb' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Rb' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Rb' ) ,       DISPLAY_ORDER = 33,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Rb'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Rn' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Rn' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Rn' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Rn' ) ,       DISPLAY_ORDER = 34,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Rn'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Rr' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Rr' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Rr' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Rr' ) ,       DISPLAY_ORDER = 35,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Rr'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Rs' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Rs' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Rs' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Rs' ) ,       DISPLAY_ORDER = 36,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Rs'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sa' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sa' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sa' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sa' ) ,       DISPLAY_ORDER = 37,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sa'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sc' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sc' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sc' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sc' ) ,       DISPLAY_ORDER = 38,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sc'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sd' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sd' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sd' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sd' ) ,       DISPLAY_ORDER = 39,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sd'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sf' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sf' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sf' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sf' ) ,       DISPLAY_ORDER = 40,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sf'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sg' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sg' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sg' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sg' ) ,       DISPLAY_ORDER = 41,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sg'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sh' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sh' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sh' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sh' ) ,       DISPLAY_ORDER = 42,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sh'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Si' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Si' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Si' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Si' ) ,       DISPLAY_ORDER = 43,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Si'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sm' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sm' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sm' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sm' ) ,       DISPLAY_ORDER = 44,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sm'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sn' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sn' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sn' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sn' ) ,       DISPLAY_ORDER = 45,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sn'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'So' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'So' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'So' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'So' ) ,       DISPLAY_ORDER = 46,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'So'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sp' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sp' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sp' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sp' ) ,       DISPLAY_ORDER = 47,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sp'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sr' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sr' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sr' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sr' ) ,       DISPLAY_ORDER = 48,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sr'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ss' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ss' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ss' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ss' ) ,       DISPLAY_ORDER = 49,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ss'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'St' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'St' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'St' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'St' ) ,       DISPLAY_ORDER = 50,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'St'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Su' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Su' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Su' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Su' ) ,       DISPLAY_ORDER = 51,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Su'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sw' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sw' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sw' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sw' ) ,       DISPLAY_ORDER = 52,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sw'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sw-DFAA' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sw-DFAA' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sw-DFAA' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sw-DFAA' ) ,       DISPLAY_ORDER = 53,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sw-DFAA'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Sx' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Sx' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Sx' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Sx' ) ,       DISPLAY_ORDER = 54,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Sx'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Tc' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Tc' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Tc' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Tc' ) ,       DISPLAY_ORDER = 55,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Tc'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Ts' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Ts' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Ts' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Ts' ) ,       DISPLAY_ORDER = 56,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Ts'
UPDATE  CRT_ELEMENT SET IS_ACTIVE = ( SELECT tmp.IS_ACTIVE
FROM CRT_ELEMENT_TMP tmp
WHERE tmp.CODE = 'Unknown' ) ,     PROGRAM_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM' AND a.CODE_NAME = tmp.PROGRAM AND tmp.CODE = 'Unknown' ) ,       PROGRAM_CATEGORY_LKUP_ID = ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE a.CODE_SET = 'PROGRAM_CATEGORY' AND a.CODE_NAME = tmp.PROGRAM_CATEGORY AND tmp.CODE = 'Unknown' ) ,    SERVICE_LINE_LKUP_ID =  ( SELECT a.CODE_LOOKUP_ID
FROM CRT_CODE_LOOKUP a, CRT_ELEMENT_TMP tmp
WHERE CODE_SET = 'SERVICE_LINE' AND CODE_NAME = tmp.SERVICE_LINE AND tmp.CODE = 'Unknown' ) ,       DISPLAY_ORDER = 57,       CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1  WHERE CRT_ELEMENT.CODE = 'Unknown'


--drop TMP table
DROP TABLE IF EXISTS CRT_ELEMENT_TMP


--Change duplicate QUANTITY CODE_NAME from 'Hwy - GAS/Seal Coat  (m2)' to 'Side - GAS/Seal Coat (m2)'
UPDATE  CRT_CODE_LOOKUP 
	SET 
		CODE_NAME = 'Side - GAS/Seal Coat (m2)'  ,
		CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
	WHERE
		CODE_SET = 'QUANTITY'
  AND DISPLAY_ORDER = 3