/**
	Author: Ayodeji Kuponiyi
	Date:	March 31, 2021

**/


/*
updates

	- New ED list- see confluence
	- Fiscal Year - Needs "TBD" value
	- Missing accomplishment - "Gravel in stockpile (m3)"
	- Prog Cat/Prog/Service Line - code value text and code name were flipped
	- Missing the "Program_category" from the code_set_lkup



*/

USE CRT_DEV;
GO




IF EXISTS (SELECT *
FROM [dbo].CRT_CODE_LOOKUP C
WHERE C.CODE_SET IN ('PROGRAM','PROGRAM_CATEGORY','SERVICE_LINE', 'ELECTORAL_DISTRICT'))
		BEGIN
	DELETE FROM CRT_CODE_LOOKUP WHERE CODE_SET IN ('PROGRAM','PROGRAM_CATEGORY','SERVICE_LINE','ELECTORAL_DISTRICT')
END

--Update fiscal year	
--SQL
IF EXISTS (SELECT *
FROM [dbo].CRT_CODE_LOOKUP C
WHERE C.CODE_SET = 'FISCAL_YEAR' AND C.CODE_NAME = 'TBD')
		BEGIN
	DELETE FROM CRT_CODE_LOOKUP WHERE CODE_SET = 'FISCAL_YEAR' AND CODE_NAME = 'TBD'
END

INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('FISCAL_YEAR', 'TBD', '', NULL, 19, 'STRING');


--Update Electoral_District	
--SQL
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Abbotsford-Mission', 'ABM', NULL, 1, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Abbotsford South', 'ABS', NULL, 2, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Abbotsford West', 'ABW', NULL, 3, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Boundary-Similkameen', 'BDS', NULL, 4, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Burnaby-Deer Lake', 'BND', NULL, 5, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Burnaby-Edmonds', 'BNE', NULL, 6, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Burnaby-Lougheed', 'BNL', NULL, 7, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Burnaby North', 'BNN', NULL, 8, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Cariboo-Chilcotin', 'CBC', NULL, 9, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Cariboo North', 'CBN', NULL, 10, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Chilliwack', 'CHC', NULL, 11, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Chilliwack-Kent', 'CHK', NULL, 12, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Columbia River-Revelstoke', 'CLR', NULL, 13, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Coquitlam-Burke Mountain', 'CQB', NULL, 14, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Coquitlam-Maillardville', 'CQM', NULL, 15, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Courtenay-Comox', 'CRC', NULL, 16, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Cowichan Valley', 'CWV', NULL, 17, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Delta North', 'DLN', NULL, 18, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Delta South', 'DLS', NULL, 19, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Esquimalt-Metchosin', 'ESM', NULL, 20, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Fraser-Nicola', 'FRN', NULL, 21, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kamloops-North Thompson', 'KAN', NULL, 22, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kamloops-South Thompson', 'KAS', NULL, 23, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kelowna-Lake Country', 'KLA', NULL, 24, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kelowna-Mission', 'KLM', NULL, 25, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kelowna West', 'KLW', NULL, 26, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kootenay East', 'KOE', NULL, 27, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Kootenay West', 'KOW', NULL, 28, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Langford-Juan de Fuca', 'LJF', NULL, 29, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Langley', 'LLY', NULL, 30, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Langley East', 'LYE', NULL, 31, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Maple Ridge-Mission', 'MAM', NULL, 32, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Maple Ridge-Pitt Meadows', 'MAP', NULL, 33, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Mid Island-Pacific Rim', 'MPR', NULL, 34, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Nanaimo', 'NAN', NULL, 35, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Nanaimo-North Cowichan', 'NCW', NULL, 36, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Nechako Lakes', 'NEC', NULL, 37, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Nelson-Creston', 'NEL', NULL, 38, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'New Westminster', 'NEW', NULL, 39, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'North Coast', 'NOC', NULL, 40, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'North Island', 'NOI', NULL, 41, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'North Vancouver-Lonsdale', 'NVL', NULL, 42, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'North Vancouver-Seymour', 'NVS', NULL, 43, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Oak Bay-Gordon Head', 'OBG', NULL, 44, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Parksville-Qualicum', 'PAQ', NULL, 45, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Peace River North', 'PCN', NULL, 46, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Peace River South', 'PCS', NULL, 47, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Penticton', 'PEN', NULL, 48, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Port Coquitlam', 'POC', NULL, 49, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Port Moody-Coquitlam', 'POM', NULL, 50, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Powell River-Sunshine Coast', 'POR', NULL, 51, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Prince George-Mackenzie', 'PRM', NULL, 52, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Prince George-Valemount', 'PRV', NULL, 53, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Richmond North Centre', 'RNC', NULL, 54, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Richmond-Steveston', 'RST', NULL, 55, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Richmond-Queensborough', 'RQE', NULL, 56, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Richmond South Centre', 'RSC', NULL, 57, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Saanich North and the Islands', 'SAN', NULL, 58, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Saanich South', 'SAS', NULL, 59, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Shuswap', 'SHU', NULL, 60, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Skeena', 'SKE', NULL, 61, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Stikine', 'SKN', NULL, 62, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Cloverdale', 'SRC', NULL, 63, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Fleetwood', 'SRF', NULL, 64, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Green Timbers', 'SRG', NULL, 65, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Guildford', 'SUG', NULL, 66, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Newton', 'SUN', NULL, 67, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Panorama', 'SUP', NULL, 68, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-Whalley', 'SWH', NULL, 69, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey-White Rock', 'SWR', NULL, 70, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Surrey South', 'SUS', NULL, 71, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Fairview', 'VFA', NULL, 72, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-False Creek', 'VFC', NULL, 73, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Fraserview', 'VFV', NULL, 74, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Hastings', 'VHA', NULL, 75, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Kensington', 'VKE', NULL, 76, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Kingsway', 'VKI', NULL, 77, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Langara', 'VLA', NULL, 78, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Mount Pleasant', 'VMP', NULL, 79, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Point Grey', 'VNP', NULL, 80, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-Quilchena', 'VNQ', NULL, 81, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vancouver-West End', 'VNW', NULL, 82, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Vernon-Monashee', 'VRM', NULL, 83, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Victoria-Beacon Hill', 'VTB', NULL, 84, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Victoria-Swan Lake', 'VTS', NULL, 85, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'West Vancouver-Capilano', 'WVC', NULL, 86, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'West Vancouver-Sea to Sky', 'WVS', NULL, 87, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ELECTORAL_DISTRICT', 'Unallocated', '99', NULL, 88, 'STRING');




--Missing accomplishment	

IF EXISTS (SELECT *
FROM CRT_CODE_LOOKUP
WHERE CODE_SET = 'ACCOMPLISHMENT' AND CODE_NAME = 'Gravel in Stockpile  (m3)' )
	BEGIN
	DELETE FROM CRT_CODE_LOOKUP WHERE CODE_SET = 'ACCOMPLISHMENT' AND CODE_NAME = 'Gravel in Stockpile  (m3)'
END

INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('ACCOMPLISHMENT', 'Gravel in Stockpile  (m3)', '', NULL, 14, 'STRING');



--PROGRAM	
--SQL
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'CapitalEx-Gen', 'Capital Expansion - General', NULL, 1, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Cariboo Connector', 'Cariboo Connector', NULL, 2, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Grants - Bike BC', 'Grants - Bike BC', NULL, 3, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'HRP - P3', 'Hwy Rehabilitation Program - P3', NULL, 4, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'HRP - SW', 'Slides and Washouts', NULL, 5, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'HRP-Bridges', 'Hwy Rehabilitation Program - Bridges', NULL, 6, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'HRP-Surfacing', 'Hwy Rehabilitation Program - Surfacing', NULL, 7, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Natural Gas', 'Natural Gas Road Upgrade Program', NULL, 8, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'RSIP', 'Road Safety Improvement Program', NULL, 9, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'SRIP', 'Side Road Improvement Program', NULL, 10, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Stimulus', 'Economic Recovery', NULL, 11, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Transit-Cap', 'Transit - Capital', NULL, 12, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Transit-Ops', 'Transit - Operating', NULL, 13, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Unclassified', 'Unclassified Program', NULL, 14, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM', 'Unclassified-DFAA', 'Disaster Financial Assistance Arrangements ', NULL, 15, 'STRING');


--PROGRAM_CATEGORY	
--SQL
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM_CATEGORY', 'Capital ', 'Capital Expansion', NULL, 1, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM_CATEGORY', 'Preservation', 'Rehabilitation Program Category', NULL, 2, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM_CATEGORY', 'Stimulus', 'Economic Recovery', NULL, 3, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM_CATEGORY', 'Transit', 'BC Transportation', NULL, 4, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('PROGRAM_CATEGORY', 'Unclassified', 'Unclassified Program Category', NULL, 5, 'STRING');


--SERVICE_LINE	
--SQL
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '0', 'Other', NULL, 1, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '60655', 'Transportation Policy & Programs', NULL, 2, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '61610', 'Other Maintenance Activities', NULL, 3, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62120', 'Other Highway Corridors', NULL, 4, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62154', 'Pre Project Development Fund', NULL, 5, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62163', 'Road Re-Surfacing - Side Roads', NULL, 6, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62169', 'Road Minor Betterments - Side Roads', NULL, 7, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62171', 'Electrical Works', NULL, 8, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62175', 'Bridge Repair And Maintenance', NULL, 9, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62176', 'Bridge Inspection Program', NULL, 10, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62179', 'Signs', NULL, 11, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62181', 'Slides And Washouts', NULL, 12, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62368', 'Oakanagan Valley Corridor', NULL, 13, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62385', 'Highway 1 - Kamloops To Golden', NULL, 14, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62520', 'Safety Improvements', NULL, 15, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62530', 'Guardrail And Median Barrier Installation', NULL, 16, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62535', 'Road Re-Surfacing Highways', NULL, 17, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62545', 'Road Minor Betterments Highways', NULL, 18, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62560', 'Bridge Re-Surfacing', NULL, 19, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62570', 'First Time Hard Surfacing', NULL, 20, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62590', 'Natural Gas Road Upgrades ', NULL, 21, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62610', 'Bridge Replacements', NULL, 22, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62620', 'Bridge Seismic Retrofit', NULL, 23, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62630', 'Bridge Rehabilitation', NULL, 24, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '62650', 'Concessionaire Rehab', NULL, 25, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '64553', 'BCTFA - Transit Operating', NULL, 26, 'STRING');
INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('SERVICE_LINE', '64555', 'BCTFA - Transit Capital', NULL, 27, 'STRING');


--CodeSet

IF EXISTS (SELECT *
FROM CRT_CODE_LOOKUP
WHERE CODE_SET = 'CODE_SET_LOOKUP' AND CODE_NAME = 'Program' AND CODE_VALUE_TEXT = 'PROGRAM_CATEGORY' )
		BEGIN
	DELETE FROM CRT_CODE_LOOKUP WHERE CODE_SET = 'CODE_SET_LOOKUP' AND CODE_NAME = 'Program' AND CODE_VALUE_TEXT = 'PROGRAM_CATEGORY'
END

INSERT INTO CRT_CODE_LOOKUP
	(CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
VALUES
	('CODE_SET_LOOKUP', 'Program', 'PROGRAM_CATEGORY', NULL, 15, 'STRING');



