
USE CRT_DEV;
GO

/*
Name: Ayodeji Kuponiyi
Date: April 13, 2021
*/


--Change duplicate PROGRAM CODE_VALUE_TEXT from 'Program' to 'Program Category'
  UPDATE  CRT_CODE_LOOKUP 
	SET 
		CODE_NAME = 'Program Category'  ,
		CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
		WHERE
			CODE_SET = 'CODE_SET_LOOKUP'
			AND CODE_VALUE_TEXT = 'PROGRAM_CATEGORY'


--Insert CODE_NAME Project Manager into 'CODE_SET_LOOKUP'

--DELETE FROM CRT_CODE_LOOKUP WHERE CODE_NAME = 'Project Manager'

  IF NOT EXISTS(SELECT * FROM [CRT_CODE_LOOKUP] WHERE CODE_SET = 'CODE_SET_LOOKUP'
									AND CODE_NAME = 'Project Manager')

	INSERT INTO [CRT_CODE_LOOKUP](CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_FORMAT, DISPLAY_ORDER) 
		VALUES('CODE_SET_LOOKUP', 'Project Manager', 'PROJECT_MANAGER', 'STRING', 16);