/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 12.1.0                     */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          S07_02_APP_CRT_V1.dez                           */
/* Project name:          Capital Rehabilitation Tracking Reporting       */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           Alter database script                           */
/* Created on:            2021-04-20 09:35                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Drop triggers                                                          */
/* ---------------------------------------------------------------------- */

DROP TRIGGER [dbo].[CRT_PROJECT_A_S_IUD_TR]
GO


DROP TRIGGER [dbo].[CRT_PROJECT_I_S_U_TR]
GO


DROP TRIGGER [dbo].[CRT_PROJECTI_S_I_TR]
GO


/* ---------------------------------------------------------------------- */
/* Drop foreign key constraints                                           */
/* ---------------------------------------------------------------------- */

ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_REGION_CRT_PROJECT]
GO


ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_CAP_INDX_FK]
GO


ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_NRST_TWN_FK]
GO


ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_RC_NUM_FK]
GO


ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_CODE_LOOKUP_CRT_PROJECT_PRJ_MGR_FK]
GO


ALTER TABLE [dbo].[CRT_FIN_TARGET] DROP CONSTRAINT [CRT_PROJECT_CRT_FIN_TARGET]
GO


ALTER TABLE [dbo].[CRT_NOTE] DROP CONSTRAINT [CRT_PROJECT_CRT_NOTE]
GO


ALTER TABLE [dbo].[CRT_QTY_ACCMP] DROP CONSTRAINT [CRT_PROJECT_CRT_QTY_ACCMP]
GO


ALTER TABLE [dbo].[CRT_RATIO] DROP CONSTRAINT [CRT_PROJECT_CRT_RATIO]
GO


ALTER TABLE [dbo].[CRT_SEGMENT] DROP CONSTRAINT [CRT_PROJECT_CRT_SEGMENT]
GO


ALTER TABLE [dbo].[CRT_TENDER] DROP CONSTRAINT [CRT_PROJECT_CRT_TENDER]
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.CRT_PROJECT"                              */
/* ---------------------------------------------------------------------- */

ALTER TABLE [dbo].[CRT_PROJECT] DROP CONSTRAINT [CRT_PROJECT_PK]
GO


CREATE TABLE [dbo].[CRT_PROJECT_TMP] (
    [PROJECT_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [CRT_PROJECT_ID_SEQ] NOT NULL,
    [PROJECT_NUMBER] VARCHAR(50) NOT NULL,
    [PROJECT_NAME] VARCHAR(255) NOT NULL,
    [DESCRIPTION] VARCHAR(2000),
    [SCOPE] VARCHAR(2000),
    [REGION_ID] NUMERIC(9) NOT NULL,
    [CAP_INDX_LKUP_ID] NUMERIC(9),
    [NEARST_TWN_LKUP_ID] NUMERIC(9),
    [RC_LKUP_ID] NUMERIC(9),
    [PROJECT_MGR_LKUP_ID] NUMERIC(9),
    [ANNCMENT_VALUE] NUMERIC(12,2),
    [C035_VALUE] NUMERIC(12,2),
    [ESTIMATED_VALUE] NUMERIC(12,2),
    [ANNCMENT_COMMENT] VARCHAR(max),
    [END_DATE] DATETIME,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


INSERT INTO [dbo].[CRT_PROJECT_TMP]
    ([PROJECT_ID],[PROJECT_NUMBER],[PROJECT_NAME],[DESCRIPTION],[SCOPE],[REGION_ID],[CAP_INDX_LKUP_ID],[NEARST_TWN_LKUP_ID],[RC_LKUP_ID],[PROJECT_MGR_LKUP_ID],[ANNCMENT_VALUE],[C035_VALUE],[ANNCMENT_COMMENT],[END_DATE],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [PROJECT_ID],[PROJECT_NUMBER],[PROJECT_NAME],[DESCRIPTION],[SCOPE],[REGION_ID],[CAP_INDX_LKUP_ID],[NEARST_TWN_LKUP_ID],[RC_LKUP_ID],[PROJECT_MGR_LKUP_ID],[ANNCMENT_VALUE],[C035_VALUE],[ANNCMENT_COMMENT],[END_DATE],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[CRT_PROJECT]
GO


DROP INDEX [dbo].[CRT_PROJECT].[CRT_PROJECT_FK_I]
GO


DROP TABLE [dbo].[CRT_PROJECT]
GO


EXEC sp_rename '[dbo].[CRT_PROJECT_TMP]', 'CRT_PROJECT', 'OBJECT'
GO


ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_PROJECT_PK] 
    PRIMARY KEY CLUSTERED ([PROJECT_ID])
GO


CREATE NONCLUSTERED INDEX [CRT_PROJECT_FK_I] ON [dbo].[CRT_PROJECT] ([PROJECT_NUMBER] ASC,[CAP_INDX_LKUP_ID] ASC,[NEARST_TWN_LKUP_ID] ASC,[RC_LKUP_ID] ASC,[PROJECT_MGR_LKUP_ID] ASC)
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Project Value determined through available information, in the absence of formal announcement and/or C-035 Values', 'SCHEMA', N'dbo', 'TABLE', N'CRT_PROJECT', 'COLUMN', N'ESTIMATED_VALUE'
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.CRT_PROJECT_HIST"                         */
/* ---------------------------------------------------------------------- */

ALTER TABLE [dbo].[CRT_PROJECT_HIST] DROP CONSTRAINT [CRT_PROJECT_HIST_PK]
GO


ALTER TABLE [dbo].[CRT_PROJECT_HIST] DROP CONSTRAINT [CRT_PROJECT_H_UK]
GO


CREATE TABLE [dbo].[CRT_PROJECT_HIST_TMP] (
    [PROJECT_HIST_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [CRT_PROJECT_H_ID_SEQ] NOT NULL,
    [PROJECT_ID] NUMERIC(9) NOT NULL,
    [PROJECT_NUMBER] VARCHAR(50) NOT NULL,
    [PROJECT_NAME] VARCHAR(255) NOT NULL,
    [DESCRIPTION] VARCHAR(2000),
    [SCOPE] VARCHAR(2000),
    [REGION_ID] NUMERIC(9) NOT NULL,
    [CAP_INDX_LKUP_ID] NUMERIC(9),
    [NEARST_TWN_LKUP_ID] VARCHAR(9),
    [RC_LKUP_ID] NUMERIC(9),
    [PROJECT_MGR_LKUP_ID] NUMERIC(9),
    [ANNCMENT_VALUE] NUMERIC(12,2),
    [C035_VALUE] NUMERIC(12,2),
    [ESTIMATED_VALUE] NUMERIC(12,2),
    [ANNCMENT_COMMENT] VARCHAR(max),
    [END_DATE] DATETIME,
    [END_DATE_HIST] DATETIME,
    [EFFECTIVE_DATE_HIST] DATETIME DEFAULT getutcdate() NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


INSERT INTO [dbo].[CRT_PROJECT_HIST_TMP]
    ([PROJECT_HIST_ID],[PROJECT_ID],[PROJECT_NUMBER],[PROJECT_NAME],[DESCRIPTION],[SCOPE],[REGION_ID],[CAP_INDX_LKUP_ID],[NEARST_TWN_LKUP_ID],[RC_LKUP_ID],[PROJECT_MGR_LKUP_ID],[ANNCMENT_VALUE],[C035_VALUE],[ANNCMENT_COMMENT],[END_DATE],[END_DATE_HIST],[EFFECTIVE_DATE_HIST],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [PROJECT_HIST_ID],[PROJECT_ID],[PROJECT_NUMBER],[PROJECT_NAME],[DESCRIPTION],[SCOPE],[REGION_ID],[CAP_INDX_LKUP_ID],[NEARST_TWN_LKUP_ID],[RC_LKUP_ID],[PROJECT_MGR_LKUP_ID],[ANNCMENT_VALUE],[C035_VALUE],[ANNCMENT_COMMENT],[END_DATE],[END_DATE_HIST],[EFFECTIVE_DATE_HIST],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[CRT_PROJECT_HIST]
GO


DROP TABLE [dbo].[CRT_PROJECT_HIST]
GO


EXEC sp_rename '[dbo].[CRT_PROJECT_HIST_TMP]', 'CRT_PROJECT_HIST', 'OBJECT'
GO


ALTER TABLE [dbo].[CRT_PROJECT_HIST] ADD CONSTRAINT [CRT_PROJECT_HIST_PK] 
    PRIMARY KEY CLUSTERED ([PROJECT_HIST_ID])
GO


ALTER TABLE [dbo].[CRT_PROJECT_HIST] ADD CONSTRAINT [CRT_PROJECT_H_UK] 
    UNIQUE ([PROJECT_HIST_ID], [END_DATE_HIST])
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Project Value determined through available information, in the absence of formal announcement and/or C-035 Values', 'SCHEMA', N'dbo', 'TABLE', N'CRT_PROJECT_HIST', 'COLUMN', N'ESTIMATED_VALUE'
GO


/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_REGION_CRT_PROJECT] 
    FOREIGN KEY ([REGION_ID]) REFERENCES [dbo].[CRT_REGION] ([REGION_ID])
GO


ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_CAP_INDX_FK] 
    FOREIGN KEY ([CAP_INDX_LKUP_ID]) REFERENCES [dbo].[CRT_CODE_LOOKUP] ([CODE_LOOKUP_ID])
GO


ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_NRST_TWN_FK] 
    FOREIGN KEY ([NEARST_TWN_LKUP_ID]) REFERENCES [dbo].[CRT_CODE_LOOKUP] ([CODE_LOOKUP_ID])
GO


ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_CODE_LOOKUP_PROJECT_RC_NUM_FK] 
    FOREIGN KEY ([RC_LKUP_ID]) REFERENCES [dbo].[CRT_CODE_LOOKUP] ([CODE_LOOKUP_ID])
GO


ALTER TABLE [dbo].[CRT_PROJECT] ADD CONSTRAINT [CRT_CODE_LOOKUP_CRT_PROJECT_PRJ_MGR_FK] 
    FOREIGN KEY ([PROJECT_MGR_LKUP_ID]) REFERENCES [dbo].[CRT_CODE_LOOKUP] ([CODE_LOOKUP_ID])
GO


ALTER TABLE [dbo].[CRT_NOTE] ADD CONSTRAINT [CRT_PROJECT_CRT_NOTE] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


ALTER TABLE [dbo].[CRT_QTY_ACCMP] ADD CONSTRAINT [CRT_PROJECT_CRT_QTY_ACCMP] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


ALTER TABLE [dbo].[CRT_FIN_TARGET] ADD CONSTRAINT [CRT_PROJECT_CRT_FIN_TARGET] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


ALTER TABLE [dbo].[CRT_TENDER] ADD CONSTRAINT [CRT_PROJECT_CRT_TENDER] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


ALTER TABLE [dbo].[CRT_SEGMENT] ADD CONSTRAINT [CRT_PROJECT_CRT_SEGMENT] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


ALTER TABLE [dbo].[CRT_RATIO] ADD CONSTRAINT [CRT_PROJECT_CRT_RATIO] 
    FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[CRT_PROJECT] ([PROJECT_ID])
GO


/* ---------------------------------------------------------------------- */
/* Repair/add triggers                                                    */
/* ---------------------------------------------------------------------- */

CREATE TRIGGER [dbo].[CRT_PROJECT_A_S_IUD_TR] ON CRT_PROJECT FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted)
    RETURN;


  IF EXISTS(SELECT * FROM deleted)
    update CRT_PROJECT_HIST set END_DATE_HIST = @curr_date where PROJECT_ID in (select PROJECT_ID from deleted) and END_DATE_HIST is null;

  IF EXISTS(SELECT * FROM inserted)
    insert into CRT_PROJECT_HIST ([PROJECT_ID], [PROJECT_NUMBER], [PROJECT_NAME], [DESCRIPTION], [SCOPE], [REGION_ID], [CAP_INDX_LKUP_ID], [NEARST_TWN_LKUP_ID], [RC_LKUP_ID], [PROJECT_MGR_LKUP_ID],[ANNCMENT_VALUE], [C035_VALUE], [ESTIMATED_VALUE], [ANNCMENT_COMMENT], [END_DATE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_GUID], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [DB_AUDIT_CREATE_USERID], [DB_AUDIT_CREATE_TIMESTAMP], [DB_AUDIT_LAST_UPDATE_USERID], [DB_AUDIT_LAST_UPDATE_TIMESTAMP], PROJECT_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [PROJECT_ID], [PROJECT_NUMBER], [PROJECT_NAME], [DESCRIPTION], [SCOPE], [REGION_ID], [CAP_INDX_LKUP_ID], [NEARST_TWN_LKUP_ID], [RC_LKUP_ID], [PROJECT_MGR_LKUP_ID], [ANNCMENT_VALUE], [C035_VALUE], [ESTIMATED_VALUE], [ANNCMENT_COMMENT], [END_DATE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_GUID], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [DB_AUDIT_CREATE_USERID], [DB_AUDIT_CREATE_TIMESTAMP], [DB_AUDIT_LAST_UPDATE_USERID], [DB_AUDIT_LAST_UPDATE_TIMESTAMP], (next value for [dbo].[CRT_PROJECT_H_ID_SEQ]) as [PROJECT_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC CRT_error_handling
END CATCH
GO


/* ---------------------------------------------------------------------- */
/* Repair/add triggers                                                    */
/* ---------------------------------------------------------------------- */

CREATE TRIGGER [dbo].[CRT_PROJECT_I_S_U_TR] ON CRT_PROJECT INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted)
    RETURN;


  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.PROJECT_ID = deleted.PROJECT_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)



  update CRT_PROJECT
    set "PROJECT_ID" = inserted."PROJECT_ID",
	  "PROJECT_NUMBER" = inserted."PROJECT_NUMBER",
	  "PROJECT_NAME" = inserted."PROJECT_NAME",
	  "DESCRIPTION" = inserted."DESCRIPTION",
	  "SCOPE" = inserted."SCOPE",
	  "REGION_ID" = inserted."REGION_ID",
	  "CAP_INDX_LKUP_ID" = inserted."CAP_INDX_LKUP_ID",
	  "NEARST_TWN_LKUP_ID" = inserted."NEARST_TWN_LKUP_ID",
	  "RC_LKUP_ID" = inserted."RC_LKUP_ID",
	  "PROJECT_MGR_LKUP_ID" = inserted."PROJECT_MGR_LKUP_ID",
	  "ANNCMENT_VALUE " = inserted."ANNCMENT_VALUE ",
	  "C035_VALUE" = inserted."C035_VALUE",       
	  "ESTIMATED_VALUE" = inserted."ESTIMATED_VALUE",
	  "ANNCMENT_COMMENT" = inserted."ANNCMENT_COMMENT",
	  "END_DATE" = inserted."END_DATE",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID"
    , DB_AUDIT_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_AUDIT_LAST_UPDATE_USERID = user_name()
    from CRT_PROJECT
    inner join inserted
    on (CRT_PROJECT.PROJECT_ID = inserted.PROJECT_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC crt_error_handling
END CATCH
GO


CREATE TRIGGER [dbo].[CRT_PROJECTI_S_I_TR] ON CRT_PROJECT INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted)
    RETURN;

  insert into CRT_PROJECT ("PROJECT_ID",
	  "PROJECT_NUMBER",
	  "PROJECT_NAME",
	  "DESCRIPTION",
	  "SCOPE",
	  "REGION_ID",
	  "CAP_INDX_LKUP_ID",
	  "NEARST_TWN_LKUP_ID",
	  "RC_LKUP_ID",
	  "PROJECT_MGR_LKUP_ID",
      "ANNCMENT_VALUE",
	  "C035_VALUE",
	  "ESTIMATED_VALUE",
	  "ANNCMENT_COMMENT",
	  "END_DATE",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID")
    select "PROJECT_ID",
	  "PROJECT_NUMBER",
	  "PROJECT_NAME",
	  "DESCRIPTION",
	  "SCOPE",
	  "REGION_ID",
	  "CAP_INDX_LKUP_ID",
	  "NEARST_TWN_LKUP_ID",
	  "RC_LKUP_ID",
	  "PROJECT_MGR_LKUP_ID",
      "ANNCMENT_VALUE",
	  "C035_VALUE",
	  "ESTIMATED_VALUE",
	  "ANNCMENT_COMMENT",
	  "END_DATE",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC CRT_error_handling
END CATCH
GO

