USE CRT_DEV;
GO

   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Lower Mainland/Southwest',    CODE_VALUE_TEXT = '5920',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Lower Mainland' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Thompson Okanagan',    CODE_VALUE_TEXT = '5930',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Thompson Okanagan' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Cariboo',    CODE_VALUE_TEXT = '5950',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Cariboo' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Kootenay',    CODE_VALUE_TEXT = '5940',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Kootenays' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Vancouver Island and Coast',    CODE_VALUE_TEXT = '5910',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Vancouver Island' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Nechako',    CODE_VALUE_TEXT = '5970',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'North Central' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'North Coast',    CODE_VALUE_TEXT = '5960',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'North West' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Northeast',    CODE_VALUE_TEXT = '5980',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'North East' 
   UPDATE CRT_CODE_LOOKUP  SET CODE_NAME = 'Province',    CODE_VALUE_TEXT = '99',   CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1 WHERE CODE_SET = 'ECONOMIC_REGION' AND CODE_NAME = 'Province' 

GO