apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: twm-config
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: true
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: ${NAME}:${VERSION}
              name: twm
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU}
                  memory: ${MEMORY}
                limits:
                  cpu: ${CPU}
                  memory: ${MEMORY}
              env:
                - name: CLIENT_SSO_HOST
                  valueFrom:
                    secretKeyRef:
                      name: sso-configs-${ENV}
                      key: CLIENT_SSO_HOST
                - name: CLIENT_SSO_REALM
                  valueFrom:
                    secretKeyRef:
                      name: sso-configs-${ENV}
                      key: CLIENT_SSO_REALM
                - name: CLIENT_SSO_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      name: sso-configs-${ENV}
                      key: CLIENT_SSO_CLIENTID
                - name: CRT_DEPLOY_SUFFIX
                  value: ${SUFFIX}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - twm
            from:
              kind: ImageStreamTag
              name: ${NAME}:${VERSION}
          type: ImageChange
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
parameters:
  - description: Name of the project (CRT)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "crt"
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: "twm"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: Environment short name (dev,test,uat,prod)
    displayName: ENV
    name: ENV
    required: false
    value: "dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: true
    value: "v1.0.0"
  - description: HOST
    displayName: HOST
    name: HOST
    required: true
    value: ""
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ""
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: ""
  - description: CPU
    displayName: CPU Request
    name: CPU
    required: true
    value: ""
  - description: MEMORY
    displayName: MEMORY Request
    name: MEMORY
    required: true
    value: ""
